#!/bin/bash

set -euo pipefail

SYSTEM=$(go env GOOS)
MODULE=github.com/Iori372552686/game_protocol
BIN_DIR=.bin
PROTOC=../lib/contrib/protoc/protoc-33.2-linux-x86_64/bin/protoc
PROTOC_INCLUDE=../lib/contrib/protoc/protoc-33.2-linux-x86_64/include
PROTOC_GO_INJECT_TAG=${BIN_DIR}/protoc-go-inject-tag
PROTOC_GEN_GO=${BIN_DIR}/protoc-gen-go

if [ "${SYSTEM}" = "darwin" ]; then
    PROTOC=../lib/contrib/protoc/protoc-33.2-osx-aarch_64/bin/protoc
    PROTOC_INCLUDE=../lib/contrib/protoc/protoc-33.2-osx-aarch_64/include
elif [ "${SYSTEM}" = "windows" ]; then
    PROTOC_GO_INJECT_TAG=${BIN_DIR}/protoc-go-inject-tag.exe
    PROTOC=../lib/contrib/protoc/protoc-33.2-win64/bin/protoc.exe
    PROTOC_INCLUDE=../lib/contrib/protoc/protoc-33.2-win64/include
    PROTOC_GEN_GO=${BIN_DIR}/protoc-gen-go.exe
fi

mkdir -p "${BIN_DIR}"
go build -o "${PROTOC_GEN_GO}" google.golang.org/protobuf/cmd/protoc-gen-go
go build -o "${PROTOC_GO_INJECT_TAG}" github.com/favadi/protoc-go-inject-tag

# Protocol-owned protos live under game_protocol/proto/{core,config,storage,svc,rpc}/.
# Generated Go stays in game_protocol/protocol.
# Service protos with go_package pointing at GoOne/api/gen are generated by
# the main repo's `go run ./tools/cmd/genproto` and must be excluded here.
PROTO_FILES=()
while IFS= read -r f; do
  [[ -f "${f}" ]] || continue
  if grep -q 'github.com/Iori372552686/GoOne/api/gen/' "${f}"; then
    continue
  fi
  PROTO_FILES+=("${f}")
done < <(find proto -name '*.proto' -type f | sort)

if [ "${#PROTO_FILES[@]}" -eq 0 ]; then
    echo "no protocol-owned proto files found"
    exit 0
fi

rm -rf ./protocol
"${PROTOC}" -I. -I"${PROTOC_INCLUDE}" \
    --plugin=protoc-gen-go="${PROTOC_GEN_GO}" \
    --go_out=. \
    --go_opt=module="${MODULE}" \
    --go_opt=paths=import \
    "${PROTO_FILES[@]}"

cp -f index.gen.go ./protocol/index.gen.go

if [ -f "./protocol/database.pb.go" ]; then
    "${PROTOC_GO_INJECT_TAG}" -input=./protocol/database.pb.go
fi
