// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: chatsvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel    int32       `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"` // in common.proto
	Sender     uint64      `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderIcon *PbIconDesc `protobuf:"bytes,3,opt,name=sender_icon,json=senderIcon,proto3" json:"sender_icon,omitempty"`
	Receiver   uint64      `protobuf:"varint,4,opt,name=receiver,proto3" json:"receiver,omitempty"` // 好友聊天要设置
	Msg        string      `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`           // 消息
}

func (x *PbChatMsg) Reset() {
	*x = PbChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbChatMsg) ProtoMessage() {}

func (x *PbChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chatsvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbChatMsg.ProtoReflect.Descriptor instead.
func (*PbChatMsg) Descriptor() ([]byte, []int) {
	return file_chatsvr_proto_rawDescGZIP(), []int{0}
}

func (x *PbChatMsg) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PbChatMsg) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *PbChatMsg) GetSenderIcon() *PbIconDesc {
	if x != nil {
		return x.SenderIcon
	}
	return nil
}

func (x *PbChatMsg) GetReceiver() uint64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *PbChatMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PbChatFriendMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendUid uint64       `protobuf:"varint,1,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	MsgList   []*PbChatMsg `protobuf:"bytes,2,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
}

func (x *PbChatFriendMsg) Reset() {
	*x = PbChatFriendMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbChatFriendMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbChatFriendMsg) ProtoMessage() {}

func (x *PbChatFriendMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chatsvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbChatFriendMsg.ProtoReflect.Descriptor instead.
func (*PbChatFriendMsg) Descriptor() ([]byte, []int) {
	return file_chatsvr_proto_rawDescGZIP(), []int{1}
}

func (x *PbChatFriendMsg) GetFriendUid() uint64 {
	if x != nil {
		return x.FriendUid
	}
	return 0
}

func (x *PbChatFriendMsg) GetMsgList() []*PbChatMsg {
	if x != nil {
		return x.MsgList
	}
	return nil
}

type PbChatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid           uint64             `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FriendMsgList []*PbChatFriendMsg `protobuf:"bytes,2,rep,name=friend_msg_list,json=friendMsgList,proto3" json:"friend_msg_list,omitempty"`
}

func (x *PbChatInfo) Reset() {
	*x = PbChatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbChatInfo) ProtoMessage() {}

func (x *PbChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatsvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbChatInfo.ProtoReflect.Descriptor instead.
func (*PbChatInfo) Descriptor() ([]byte, []int) {
	return file_chatsvr_proto_rawDescGZIP(), []int{2}
}

func (x *PbChatInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PbChatInfo) GetFriendMsgList() []*PbChatFriendMsg {
	if x != nil {
		return x.FriendMsgList
	}
	return nil
}

var File_chatsvr_proto protoreflect.FileDescriptor

var file_chatsvr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0a, 0x72, 0x6f,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x09, 0x50, 0x62, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x49, 0x63,
	0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x63,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x63, 0x0a, 0x0f, 0x50, 0x62, 0x43, 0x68, 0x61, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x55,
	0x69, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x0a, 0x50, 0x62, 0x43, 0x68, 0x61, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x44, 0x0a, 0x0f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x43,
	0x68, 0x61, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x0d, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatsvr_proto_rawDescOnce sync.Once
	file_chatsvr_proto_rawDescData = file_chatsvr_proto_rawDesc
)

func file_chatsvr_proto_rawDescGZIP() []byte {
	file_chatsvr_proto_rawDescOnce.Do(func() {
		file_chatsvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatsvr_proto_rawDescData)
	})
	return file_chatsvr_proto_rawDescData
}

var file_chatsvr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chatsvr_proto_goTypes = []interface{}{
	(*PbChatMsg)(nil),       // 0: g1.protocol.PbChatMsg
	(*PbChatFriendMsg)(nil), // 1: g1.protocol.PbChatFriendMsg
	(*PbChatInfo)(nil),      // 2: g1.protocol.PbChatInfo
	(*PbIconDesc)(nil),      // 3: g1.protocol.PbIconDesc
}
var file_chatsvr_proto_depIdxs = []int32{
	3, // 0: g1.protocol.PbChatMsg.sender_icon:type_name -> g1.protocol.PbIconDesc
	0, // 1: g1.protocol.PbChatFriendMsg.msg_list:type_name -> g1.protocol.PbChatMsg
	1, // 2: g1.protocol.PbChatInfo.friend_msg_list:type_name -> g1.protocol.PbChatFriendMsg
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatsvr_proto_init() }
func file_chatsvr_proto_init() {
	if File_chatsvr_proto != nil {
		return
	}
	file_role_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chatsvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatsvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbChatFriendMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatsvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbChatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatsvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatsvr_proto_goTypes,
		DependencyIndexes: file_chatsvr_proto_depIdxs,
		MessageInfos:      file_chatsvr_proto_msgTypes,
	}.Build()
	File_chatsvr_proto = out.File
	file_chatsvr_proto_rawDesc = nil
	file_chatsvr_proto_goTypes = nil
	file_chatsvr_proto_depIdxs = nil
}
