//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: enum_config.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyType int32

const (
	PropertyType_PropertyType_Empty   PropertyType = 0 // 道具类型-空
	PropertyType_PropertyType_Coin    PropertyType = 1 // 道具类型-金币
	PropertyType_PropertyType_Diamond PropertyType = 2 // 道具类型-钻石
)

// Enum value maps for PropertyType.
var (
	PropertyType_name = map[int32]string{
		0: "PropertyType_Empty",
		1: "PropertyType_Coin",
		2: "PropertyType_Diamond",
	}
	PropertyType_value = map[string]int32{
		"PropertyType_Empty":   0,
		"PropertyType_Coin":    1,
		"PropertyType_Diamond": 2,
	}
)

func (x PropertyType) Enum() *PropertyType {
	p := new(PropertyType)
	*p = x
	return p
}

func (x PropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_config_proto_enumTypes[0].Descriptor()
}

func (PropertyType) Type() protoreflect.EnumType {
	return &file_enum_config_proto_enumTypes[0]
}

func (x PropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyType.Descriptor instead.
func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return file_enum_config_proto_rawDescGZIP(), []int{0}
}

type QualityType int32

const (
	QualityType_QualityType_None  QualityType = 0 // 品质类型-空
	QualityType_QualityType_White QualityType = 1 // 品质类型-白
	QualityType_QualityType_Blue  QualityType = 2 // 品质类型-蓝
)

// Enum value maps for QualityType.
var (
	QualityType_name = map[int32]string{
		0: "QualityType_None",
		1: "QualityType_White",
		2: "QualityType_Blue",
	}
	QualityType_value = map[string]int32{
		"QualityType_None":  0,
		"QualityType_White": 1,
		"QualityType_Blue":  2,
	}
)

func (x QualityType) Enum() *QualityType {
	p := new(QualityType)
	*p = x
	return p
}

func (x QualityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QualityType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_config_proto_enumTypes[1].Descriptor()
}

func (QualityType) Type() protoreflect.EnumType {
	return &file_enum_config_proto_enumTypes[1]
}

func (x QualityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QualityType.Descriptor instead.
func (QualityType) EnumDescriptor() ([]byte, []int) {
	return file_enum_config_proto_rawDescGZIP(), []int{1}
}

type TaskType int32

const (
	TaskType_TaskType_NONE TaskType = 0 // 任务类型-空
	TaskType_TaskType_MAIN TaskType = 1 // 任务类型-主线
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TaskType_NONE",
		1: "TaskType_MAIN",
	}
	TaskType_value = map[string]int32{
		"TaskType_NONE": 0,
		"TaskType_MAIN": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_config_proto_enumTypes[2].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_enum_config_proto_enumTypes[2]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_enum_config_proto_rawDescGZIP(), []int{2}
}

var File_enum_config_proto protoreflect.FileDescriptor

var file_enum_config_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2a, 0x57, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x6f, 0x69, 0x6e, 0x10, 0x01, 0x12,
	0x18, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x10, 0x02, 0x2a, 0x50, 0x0a, 0x0b, 0x51, 0x75, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x51, 0x75, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x11, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x6c, 0x75, 0x65, 0x10, 0x02, 0x2a, 0x30, 0x0a, 0x08, 0x54,
	0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x61,
	0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x42, 0x0f, 0x5a,
	0x0d, 0x2e, 0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_config_proto_rawDescOnce sync.Once
	file_enum_config_proto_rawDescData = file_enum_config_proto_rawDesc
)

func file_enum_config_proto_rawDescGZIP() []byte {
	file_enum_config_proto_rawDescOnce.Do(func() {
		file_enum_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_config_proto_rawDescData)
	})
	return file_enum_config_proto_rawDescData
}

var file_enum_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_enum_config_proto_goTypes = []interface{}{
	(PropertyType)(0), // 0: g1.protocol.PropertyType
	(QualityType)(0),  // 1: g1.protocol.QualityType
	(TaskType)(0),     // 2: g1.protocol.TaskType
}
var file_enum_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_config_proto_init() }
func file_enum_config_proto_init() {
	if File_enum_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_config_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_config_proto_goTypes,
		DependencyIndexes: file_enum_config_proto_depIdxs,
		EnumInfos:         file_enum_config_proto_enumTypes,
	}.Build()
	File_enum_config_proto = out.File
	file_enum_config_proto_rawDesc = nil
	file_enum_config_proto_goTypes = nil
	file_enum_config_proto_depIdxs = nil
}
