// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: friendsvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *PbFriend) Reset() {
	*x = PbFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbFriend) ProtoMessage() {}

func (x *PbFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbFriend.ProtoReflect.Descriptor instead.
func (*PbFriend) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{0}
}

func (x *PbFriend) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PbFriendInvitation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	InviteTime int32  `protobuf:"varint,2,opt,name=invite_time,json=inviteTime,proto3" json:"invite_time,omitempty"`
}

func (x *PbFriendInvitation) Reset() {
	*x = PbFriendInvitation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbFriendInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbFriendInvitation) ProtoMessage() {}

func (x *PbFriendInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbFriendInvitation.ProtoReflect.Descriptor instead.
func (*PbFriendInvitation) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{1}
}

func (x *PbFriendInvitation) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PbFriendInvitation) GetInviteTime() int32 {
	if x != nil {
		return x.InviteTime
	}
	return 0
}

type RoleFriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid            uint64                `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FriendList     []*PbFriend           `protobuf:"bytes,2,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	BlackList      []uint64              `protobuf:"varint,3,rep,packed,name=black_list,json=blackList,proto3" json:"black_list,omitempty"`
	InvitationList []*PbFriendInvitation `protobuf:"bytes,4,rep,name=invitation_list,json=invitationList,proto3" json:"invitation_list,omitempty"`
}

func (x *RoleFriendInfo) Reset() {
	*x = RoleFriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleFriendInfo) ProtoMessage() {}

func (x *RoleFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleFriendInfo.ProtoReflect.Descriptor instead.
func (*RoleFriendInfo) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{2}
}

func (x *RoleFriendInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoleFriendInfo) GetFriendList() []*PbFriend {
	if x != nil {
		return x.FriendList
	}
	return nil
}

func (x *RoleFriendInfo) GetBlackList() []uint64 {
	if x != nil {
		return x.BlackList
	}
	return nil
}

func (x *RoleFriendInfo) GetInvitationList() []*PbFriendInvitation {
	if x != nil {
		return x.InvitationList
	}
	return nil
}

// FRIEND_INNER_ADD_FRIEND_REQ
type FriendInnerAddFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid     uint64 `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	IsDelFriend bool   `protobuf:"varint,2,opt,name=is_del_friend,json=isDelFriend,proto3" json:"is_del_friend,omitempty"`
}

func (x *FriendInnerAddFriendReq) Reset() {
	*x = FriendInnerAddFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInnerAddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInnerAddFriendReq) ProtoMessage() {}

func (x *FriendInnerAddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInnerAddFriendReq.ProtoReflect.Descriptor instead.
func (*FriendInnerAddFriendReq) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{3}
}

func (x *FriendInnerAddFriendReq) GetFromUid() uint64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *FriendInnerAddFriendReq) GetIsDelFriend() bool {
	if x != nil {
		return x.IsDelFriend
	}
	return false
}

type FriendInnerAddFriendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *FriendInnerAddFriendRsp) Reset() {
	*x = FriendInnerAddFriendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInnerAddFriendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInnerAddFriendRsp) ProtoMessage() {}

func (x *FriendInnerAddFriendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInnerAddFriendRsp.ProtoReflect.Descriptor instead.
func (*FriendInnerAddFriendRsp) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{4}
}

func (x *FriendInnerAddFriendRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// FRIEND_INNER_CONFIRM_FRIEND_REQ
type FriendInnerConfirmFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid  uint64 `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	FromName string `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	IsReject bool   `protobuf:"varint,3,opt,name=is_reject,json=isReject,proto3" json:"is_reject,omitempty"`
}

func (x *FriendInnerConfirmFriendReq) Reset() {
	*x = FriendInnerConfirmFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInnerConfirmFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInnerConfirmFriendReq) ProtoMessage() {}

func (x *FriendInnerConfirmFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInnerConfirmFriendReq.ProtoReflect.Descriptor instead.
func (*FriendInnerConfirmFriendReq) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{5}
}

func (x *FriendInnerConfirmFriendReq) GetFromUid() uint64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *FriendInnerConfirmFriendReq) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *FriendInnerConfirmFriendReq) GetIsReject() bool {
	if x != nil {
		return x.IsReject
	}
	return false
}

type FriendInnerConfirmFriendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *FriendInnerConfirmFriendRsp) Reset() {
	*x = FriendInnerConfirmFriendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendsvr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInnerConfirmFriendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInnerConfirmFriendRsp) ProtoMessage() {}

func (x *FriendInnerConfirmFriendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_friendsvr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInnerConfirmFriendRsp.ProtoReflect.Descriptor instead.
func (*FriendInnerConfirmFriendRsp) Descriptor() ([]byte, []int) {
	return file_friendsvr_proto_rawDescGZIP(), []int{6}
}

func (x *FriendInnerConfirmFriendRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

var File_friendsvr_proto protoreflect.FileDescriptor

var file_friendsvr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x08,
	0x50, 0x62, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x12, 0x50, 0x62,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x0b, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x48, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x17, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x22, 0x3d, 0x0a, 0x17, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x6e,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x22,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x22, 0x72, 0x0a, 0x1b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x41, 0x0a, 0x1b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x67,
	0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_friendsvr_proto_rawDescOnce sync.Once
	file_friendsvr_proto_rawDescData = file_friendsvr_proto_rawDesc
)

func file_friendsvr_proto_rawDescGZIP() []byte {
	file_friendsvr_proto_rawDescOnce.Do(func() {
		file_friendsvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_friendsvr_proto_rawDescData)
	})
	return file_friendsvr_proto_rawDescData
}

var file_friendsvr_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_friendsvr_proto_goTypes = []interface{}{
	(*PbFriend)(nil),                    // 0: g1.protocol.PbFriend
	(*PbFriendInvitation)(nil),          // 1: g1.protocol.PbFriendInvitation
	(*RoleFriendInfo)(nil),              // 2: g1.protocol.RoleFriendInfo
	(*FriendInnerAddFriendReq)(nil),     // 3: g1.protocol.FriendInnerAddFriendReq
	(*FriendInnerAddFriendRsp)(nil),     // 4: g1.protocol.FriendInnerAddFriendRsp
	(*FriendInnerConfirmFriendReq)(nil), // 5: g1.protocol.FriendInnerConfirmFriendReq
	(*FriendInnerConfirmFriendRsp)(nil), // 6: g1.protocol.FriendInnerConfirmFriendRsp
	(*Ret)(nil),                         // 7: g1.protocol.Ret
}
var file_friendsvr_proto_depIdxs = []int32{
	0, // 0: g1.protocol.RoleFriendInfo.friend_list:type_name -> g1.protocol.PbFriend
	1, // 1: g1.protocol.RoleFriendInfo.invitation_list:type_name -> g1.protocol.PbFriendInvitation
	7, // 2: g1.protocol.FriendInnerAddFriendRsp.ret:type_name -> g1.protocol.Ret
	7, // 3: g1.protocol.FriendInnerConfirmFriendRsp.ret:type_name -> g1.protocol.Ret
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_friendsvr_proto_init() }
func file_friendsvr_proto_init() {
	if File_friendsvr_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_friendsvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendsvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbFriendInvitation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendsvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleFriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendsvr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInnerAddFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendsvr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInnerAddFriendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendsvr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInnerConfirmFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendsvr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInnerConfirmFriendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friendsvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friendsvr_proto_goTypes,
		DependencyIndexes: file_friendsvr_proto_depIdxs,
		MessageInfos:      file_friendsvr_proto_msgTypes,
	}.Build()
	File_friendsvr_proto = out.File
	file_friendsvr_proto_rawDesc = nil
	file_friendsvr_proto_goTypes = nil
	file_friendsvr_proto_depIdxs = nil
}
