//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: global_config.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`       // 字段ID
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`    // 字段名称
	Value int32  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"` // 值
	Desc  string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`    // 描述
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_global_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_global_config_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalConfig) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GlobalConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GlobalConfig) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GlobalConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type GlobalConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*GlobalConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *GlobalConfigAry) Reset() {
	*x = GlobalConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfigAry) ProtoMessage() {}

func (x *GlobalConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_global_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfigAry.ProtoReflect.Descriptor instead.
func (*GlobalConfigAry) Descriptor() ([]byte, []int) {
	return file_global_config_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalConfigAry) GetAry() []*GlobalConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_global_config_proto protoreflect.FileDescriptor

var file_global_config_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x22, 0x5c, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x22, 0x3e, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x41, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_config_proto_rawDescOnce sync.Once
	file_global_config_proto_rawDescData = file_global_config_proto_rawDesc
)

func file_global_config_proto_rawDescGZIP() []byte {
	file_global_config_proto_rawDescOnce.Do(func() {
		file_global_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_config_proto_rawDescData)
	})
	return file_global_config_proto_rawDescData
}

var file_global_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_global_config_proto_goTypes = []interface{}{
	(*GlobalConfig)(nil),    // 0: g1.protocol.GlobalConfig
	(*GlobalConfigAry)(nil), // 1: g1.protocol.GlobalConfigAry
}
var file_global_config_proto_depIdxs = []int32{
	0, // 0: g1.protocol.GlobalConfigAry.Ary:type_name -> g1.protocol.GlobalConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_global_config_proto_init() }
func file_global_config_proto_init() {
	if File_global_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_global_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_config_proto_goTypes,
		DependencyIndexes: file_global_config_proto_depIdxs,
		MessageInfos:      file_global_config_proto_msgTypes,
	}.Build()
	File_global_config_proto = out.File
	file_global_config_proto_rawDesc = nil
	file_global_config_proto_goTypes = nil
	file_global_config_proto_depIdxs = nil
}
