// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: gm.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MAIN_GM_GET_ROLE_REQ
type GMGetRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GMGetRoleReq) Reset() {
	*x = GMGetRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMGetRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMGetRoleReq) ProtoMessage() {}

func (x *GMGetRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMGetRoleReq.ProtoReflect.Descriptor instead.
func (*GMGetRoleReq) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{0}
}

type GMGetRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *Ret      `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	RoleInfo *RoleInfo `protobuf:"bytes,2,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
}

func (x *GMGetRoleRsp) Reset() {
	*x = GMGetRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMGetRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMGetRoleRsp) ProtoMessage() {}

func (x *GMGetRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMGetRoleRsp.ProtoReflect.Descriptor instead.
func (*GMGetRoleRsp) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{1}
}

func (x *GMGetRoleRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *GMGetRoleRsp) GetRoleInfo() *RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

// MAIN_GM_SET_ROLE_REQ
type GMSetRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleInfo *RoleInfo `protobuf:"bytes,1,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
}

func (x *GMSetRoleReq) Reset() {
	*x = GMSetRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMSetRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMSetRoleReq) ProtoMessage() {}

func (x *GMSetRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMSetRoleReq.ProtoReflect.Descriptor instead.
func (*GMSetRoleReq) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{2}
}

func (x *GMSetRoleReq) GetRoleInfo() *RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

type GMSetRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *GMSetRoleRsp) Reset() {
	*x = GMSetRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMSetRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMSetRoleRsp) ProtoMessage() {}

func (x *GMSetRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMSetRoleRsp.ProtoReflect.Descriptor instead.
func (*GMSetRoleRsp) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{3}
}

func (x *GMSetRoleRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// MAIN_GM_ADD_ITEM_REQ
type GMAddItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GMAddItemReq) Reset() {
	*x = GMAddItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMAddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMAddItemReq) ProtoMessage() {}

func (x *GMAddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMAddItemReq.ProtoReflect.Descriptor instead.
func (*GMAddItemReq) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{4}
}

func (x *GMAddItemReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GMAddItemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GMAddItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *GMAddItemRsp) Reset() {
	*x = GMAddItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMAddItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMAddItemRsp) ProtoMessage() {}

func (x *GMAddItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMAddItemRsp.ProtoReflect.Descriptor instead.
func (*GMAddItemRsp) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{5}
}

func (x *GMAddItemRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

var File_gm_proto protoreflect.FileDescriptor

var file_gm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x22, 0x66, 0x0a, 0x0c, 0x47, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x42, 0x0a, 0x0c, 0x47, 0x4d, 0x53,
	0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x09, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x32, 0x0a,
	0x0c, 0x47, 0x4d, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65,
	0x74, 0x22, 0x34, 0x0a, 0x0c, 0x47, 0x4d, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x0c, 0x47, 0x4d, 0x41, 0x64, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gm_proto_rawDescOnce sync.Once
	file_gm_proto_rawDescData = file_gm_proto_rawDesc
)

func file_gm_proto_rawDescGZIP() []byte {
	file_gm_proto_rawDescOnce.Do(func() {
		file_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gm_proto_rawDescData)
	})
	return file_gm_proto_rawDescData
}

var file_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gm_proto_goTypes = []interface{}{
	(*GMGetRoleReq)(nil), // 0: g1.protocol.GMGetRoleReq
	(*GMGetRoleRsp)(nil), // 1: g1.protocol.GMGetRoleRsp
	(*GMSetRoleReq)(nil), // 2: g1.protocol.GMSetRoleReq
	(*GMSetRoleRsp)(nil), // 3: g1.protocol.GMSetRoleRsp
	(*GMAddItemReq)(nil), // 4: g1.protocol.GMAddItemReq
	(*GMAddItemRsp)(nil), // 5: g1.protocol.GMAddItemRsp
	(*Ret)(nil),          // 6: g1.protocol.Ret
	(*RoleInfo)(nil),     // 7: g1.protocol.RoleInfo
}
var file_gm_proto_depIdxs = []int32{
	6, // 0: g1.protocol.GMGetRoleRsp.ret:type_name -> g1.protocol.Ret
	7, // 1: g1.protocol.GMGetRoleRsp.role_info:type_name -> g1.protocol.RoleInfo
	7, // 2: g1.protocol.GMSetRoleReq.role_info:type_name -> g1.protocol.RoleInfo
	6, // 3: g1.protocol.GMSetRoleRsp.ret:type_name -> g1.protocol.Ret
	6, // 4: g1.protocol.GMAddItemRsp.ret:type_name -> g1.protocol.Ret
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gm_proto_init() }
func file_gm_proto_init() {
	if File_gm_proto != nil {
		return
	}
	file_role_proto_init()
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMGetRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMGetRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMSetRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMSetRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMAddItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMAddItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gm_proto_goTypes,
		DependencyIndexes: file_gm_proto_depIdxs,
		MessageInfos:      file_gm_proto_msgTypes,
	}.Build()
	File_gm_proto = out.File
	file_gm_proto_rawDesc = nil
	file_gm_proto_goTypes = nil
	file_gm_proto_depIdxs = nil
}
