// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: infosvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbRoleBriefInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid            uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl        string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Frame          int32  `protobuf:"varint,4,opt,name=frame,proto3" json:"frame,omitempty"`
	Level          int32  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel       int32  `protobuf:"varint,6,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	Exp            int32  `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Image          int32  `protobuf:"varint,8,opt,name=image,proto3" json:"image,omitempty"`
	RegisterTime   int32  `protobuf:"varint,9,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	TotalStar      int32  `protobuf:"varint,11,opt,name=total_star,json=totalStar,proto3" json:"total_star,omitempty"`
	CardCnt        int32  `protobuf:"varint,12,opt,name=card_cnt,json=cardCnt,proto3" json:"card_cnt,omitempty"`
	Fp             int32  `protobuf:"varint,13,opt,name=fp,proto3" json:"fp,omitempty"`
	OpvpLevel      int32  `protobuf:"varint,14,opt,name=opvp_level,json=opvpLevel,proto3" json:"opvp_level,omitempty"`
	OpvpRank       int32  `protobuf:"varint,15,opt,name=opvp_rank,json=opvpRank,proto3" json:"opvp_rank,omitempty"`
	LastOnlineTime int32  `protobuf:"varint,16,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	ConnBusId      uint32 `protobuf:"varint,100,opt,name=conn_bus_id,json=connBusId,proto3" json:"conn_bus_id,omitempty"`
}

func (x *PbRoleBriefInfo) Reset() {
	*x = PbRoleBriefInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infosvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbRoleBriefInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbRoleBriefInfo) ProtoMessage() {}

func (x *PbRoleBriefInfo) ProtoReflect() protoreflect.Message {
	mi := &file_infosvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbRoleBriefInfo.ProtoReflect.Descriptor instead.
func (*PbRoleBriefInfo) Descriptor() ([]byte, []int) {
	return file_infosvr_proto_rawDescGZIP(), []int{0}
}

func (x *PbRoleBriefInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PbRoleBriefInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbRoleBriefInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PbRoleBriefInfo) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *PbRoleBriefInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PbRoleBriefInfo) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *PbRoleBriefInfo) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PbRoleBriefInfo) GetImage() int32 {
	if x != nil {
		return x.Image
	}
	return 0
}

func (x *PbRoleBriefInfo) GetRegisterTime() int32 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *PbRoleBriefInfo) GetTotalStar() int32 {
	if x != nil {
		return x.TotalStar
	}
	return 0
}

func (x *PbRoleBriefInfo) GetCardCnt() int32 {
	if x != nil {
		return x.CardCnt
	}
	return 0
}

func (x *PbRoleBriefInfo) GetFp() int32 {
	if x != nil {
		return x.Fp
	}
	return 0
}

func (x *PbRoleBriefInfo) GetOpvpLevel() int32 {
	if x != nil {
		return x.OpvpLevel
	}
	return 0
}

func (x *PbRoleBriefInfo) GetOpvpRank() int32 {
	if x != nil {
		return x.OpvpRank
	}
	return 0
}

func (x *PbRoleBriefInfo) GetLastOnlineTime() int32 {
	if x != nil {
		return x.LastOnlineTime
	}
	return 0
}

func (x *PbRoleBriefInfo) GetConnBusId() uint32 {
	if x != nil {
		return x.ConnBusId
	}
	return 0
}

// INFO_SET_BRIEF_INFO_REQ
type InfoSetBriefInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       uint64           `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Info      *PbRoleBriefInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	IgnoreRsp bool             `protobuf:"varint,3,opt,name=ignore_rsp,json=ignoreRsp,proto3" json:"ignore_rsp,omitempty"`
}

func (x *InfoSetBriefInfoReq) Reset() {
	*x = InfoSetBriefInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infosvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoSetBriefInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSetBriefInfoReq) ProtoMessage() {}

func (x *InfoSetBriefInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_infosvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSetBriefInfoReq.ProtoReflect.Descriptor instead.
func (*InfoSetBriefInfoReq) Descriptor() ([]byte, []int) {
	return file_infosvr_proto_rawDescGZIP(), []int{1}
}

func (x *InfoSetBriefInfoReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InfoSetBriefInfoReq) GetInfo() *PbRoleBriefInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *InfoSetBriefInfoReq) GetIgnoreRsp() bool {
	if x != nil {
		return x.IgnoreRsp
	}
	return false
}

type InfoSetBriefInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *InfoSetBriefInfoRsp) Reset() {
	*x = InfoSetBriefInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infosvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoSetBriefInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSetBriefInfoRsp) ProtoMessage() {}

func (x *InfoSetBriefInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_infosvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSetBriefInfoRsp.ProtoReflect.Descriptor instead.
func (*InfoSetBriefInfoRsp) Descriptor() ([]byte, []int) {
	return file_infosvr_proto_rawDescGZIP(), []int{2}
}

func (x *InfoSetBriefInfoRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

var File_infosvr_proto protoreflect.FileDescriptor

var file_infosvr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x03, 0x0a, 0x0f, 0x50,
	0x62, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x76,
	0x69, 0x70, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x76, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x6e, 0x74,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x43, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x66, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x66, 0x70, 0x12,
	0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x76, 0x70, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x70, 0x76, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x70, 0x76, 0x70, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6f, 0x70, 0x76, 0x70, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x28, 0x0a, 0x10, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x62, 0x75,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e,
	0x42, 0x75, 0x73, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x13, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x74,
	0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x30,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x52, 0x6f, 0x6c,
	0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x73, 0x70, 0x22,
	0x39, 0x0a, 0x13, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f,
	0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_infosvr_proto_rawDescOnce sync.Once
	file_infosvr_proto_rawDescData = file_infosvr_proto_rawDesc
)

func file_infosvr_proto_rawDescGZIP() []byte {
	file_infosvr_proto_rawDescOnce.Do(func() {
		file_infosvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_infosvr_proto_rawDescData)
	})
	return file_infosvr_proto_rawDescData
}

var file_infosvr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_infosvr_proto_goTypes = []interface{}{
	(*PbRoleBriefInfo)(nil),     // 0: g1.protocol.PbRoleBriefInfo
	(*InfoSetBriefInfoReq)(nil), // 1: g1.protocol.InfoSetBriefInfoReq
	(*InfoSetBriefInfoRsp)(nil), // 2: g1.protocol.InfoSetBriefInfoRsp
	(*Ret)(nil),                 // 3: g1.protocol.Ret
}
var file_infosvr_proto_depIdxs = []int32{
	0, // 0: g1.protocol.InfoSetBriefInfoReq.info:type_name -> g1.protocol.PbRoleBriefInfo
	3, // 1: g1.protocol.InfoSetBriefInfoRsp.ret:type_name -> g1.protocol.Ret
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_infosvr_proto_init() }
func file_infosvr_proto_init() {
	if File_infosvr_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_infosvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbRoleBriefInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infosvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoSetBriefInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infosvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoSetBriefInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infosvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infosvr_proto_goTypes,
		DependencyIndexes: file_infosvr_proto_depIdxs,
		MessageInfos:      file_infosvr_proto_msgTypes,
	}.Build()
	File_infosvr_proto = out.File
	file_infosvr_proto_rawDesc = nil
	file_infosvr_proto_goTypes = nil
	file_infosvr_proto_depIdxs = nil
}
