// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: mailsvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            int32     `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                               // in common.proto  MailType
	ConfId          int32     `protobuf:"varint,3,opt,name=conf_id,json=confId,proto3" json:"conf_id,omitempty"`             // 邮件配置表中id
	CreateTime      int32     `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	AttachList      []*PbItem `protobuf:"bytes,5,rep,name=attach_list,json=attachList,proto3" json:"attach_list,omitempty"`  // 邮件附件
	Sender          uint64    `protobuf:"varint,6,opt,name=sender,proto3" json:"sender,omitempty"`                           // 好友邮件需要设置uid
	Read            bool      `protobuf:"varint,10,opt,name=read,proto3" json:"read,omitempty"`                              // 是否已读
	AttachGet       bool      `protobuf:"varint,11,opt,name=attach_get,json=attachGet,proto3" json:"attach_get,omitempty"`   // 附件是否领取
	Title           string    `protobuf:"bytes,20,opt,name=title,proto3" json:"title,omitempty"`
	Content         string    `protobuf:"bytes,21,opt,name=content,proto3" json:"content,omitempty"`
	ContentArgv     []string  `protobuf:"bytes,22,rep,name=content_argv,json=contentArgv,proto3" json:"content_argv,omitempty"`
	RemoveStartTime int32     `protobuf:"varint,50,opt,name=remove_start_time,json=removeStartTime,proto3" json:"remove_start_time,omitempty"` // 邮件删除开始计时
}

func (x *PbMail) Reset() {
	*x = PbMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mailsvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMail) ProtoMessage() {}

func (x *PbMail) ProtoReflect() protoreflect.Message {
	mi := &file_mailsvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMail.ProtoReflect.Descriptor instead.
func (*PbMail) Descriptor() ([]byte, []int) {
	return file_mailsvr_proto_rawDescGZIP(), []int{0}
}

func (x *PbMail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbMail) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PbMail) GetConfId() int32 {
	if x != nil {
		return x.ConfId
	}
	return 0
}

func (x *PbMail) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PbMail) GetAttachList() []*PbItem {
	if x != nil {
		return x.AttachList
	}
	return nil
}

func (x *PbMail) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *PbMail) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *PbMail) GetAttachGet() bool {
	if x != nil {
		return x.AttachGet
	}
	return false
}

func (x *PbMail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PbMail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PbMail) GetContentArgv() []string {
	if x != nil {
		return x.ContentArgv
	}
	return nil
}

func (x *PbMail) GetRemoveStartTime() int32 {
	if x != nil {
		return x.RemoveStartTime
	}
	return 0
}

type MailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         uint64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MailList    []*PbMail `protobuf:"bytes,2,rep,name=mail_list,json=mailList,proto3" json:"mail_list,omitempty"`
	CurMailId   int32     `protobuf:"varint,3,opt,name=cur_mail_id,json=curMailId,proto3" json:"cur_mail_id,omitempty"`
	AddMailList []int32   `protobuf:"varint,4,rep,packed,name=add_mail_list,json=addMailList,proto3" json:"add_mail_list,omitempty"` // 记录配置表中已经发放的邮件，防止重复发放
}

func (x *MailInfo) Reset() {
	*x = MailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mailsvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailInfo) ProtoMessage() {}

func (x *MailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mailsvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailInfo.ProtoReflect.Descriptor instead.
func (*MailInfo) Descriptor() ([]byte, []int) {
	return file_mailsvr_proto_rawDescGZIP(), []int{1}
}

func (x *MailInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MailInfo) GetMailList() []*PbMail {
	if x != nil {
		return x.MailList
	}
	return nil
}

func (x *MailInfo) GetCurMailId() int32 {
	if x != nil {
		return x.CurMailId
	}
	return 0
}

func (x *MailInfo) GetAddMailList() []int32 {
	if x != nil {
		return x.AddMailList
	}
	return nil
}

// MAIL_INNER_ADD_MAIL_REQ
type MailInnerAddMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailList []*PbMail `protobuf:"bytes,1,rep,name=mail_list,json=mailList,proto3" json:"mail_list,omitempty"`
}

func (x *MailInnerAddMailReq) Reset() {
	*x = MailInnerAddMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mailsvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailInnerAddMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailInnerAddMailReq) ProtoMessage() {}

func (x *MailInnerAddMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_mailsvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailInnerAddMailReq.ProtoReflect.Descriptor instead.
func (*MailInnerAddMailReq) Descriptor() ([]byte, []int) {
	return file_mailsvr_proto_rawDescGZIP(), []int{2}
}

func (x *MailInnerAddMailReq) GetMailList() []*PbMail {
	if x != nil {
		return x.MailList
	}
	return nil
}

type MailInnerAddMailRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *MailInnerAddMailRsp) Reset() {
	*x = MailInnerAddMailRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mailsvr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailInnerAddMailRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailInnerAddMailRsp) ProtoMessage() {}

func (x *MailInnerAddMailRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mailsvr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailInnerAddMailRsp.ProtoReflect.Descriptor instead.
func (*MailInnerAddMailRsp) Descriptor() ([]byte, []int) {
	return file_mailsvr_proto_rawDescGZIP(), []int{3}
}

func (x *MailInnerAddMailRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

var File_mailsvr_proto protoreflect.FileDescriptor

var file_mailsvr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x72, 0x6f, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6, 0x02, 0x0a, 0x06, 0x50, 0x62, 0x4d, 0x61, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x34, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x65, 0x61,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x72, 0x67, 0x76,
	0x18, 0x16, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41,
	0x72, 0x67, 0x76, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x32, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x92, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x30,
	0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x62, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x75, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x61, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x09, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x62, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x39, 0x0a,
	0x13, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x67, 0x31,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mailsvr_proto_rawDescOnce sync.Once
	file_mailsvr_proto_rawDescData = file_mailsvr_proto_rawDesc
)

func file_mailsvr_proto_rawDescGZIP() []byte {
	file_mailsvr_proto_rawDescOnce.Do(func() {
		file_mailsvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_mailsvr_proto_rawDescData)
	})
	return file_mailsvr_proto_rawDescData
}

var file_mailsvr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mailsvr_proto_goTypes = []interface{}{
	(*PbMail)(nil),              // 0: g1.protocol.PbMail
	(*MailInfo)(nil),            // 1: g1.protocol.MailInfo
	(*MailInnerAddMailReq)(nil), // 2: g1.protocol.MailInnerAddMailReq
	(*MailInnerAddMailRsp)(nil), // 3: g1.protocol.MailInnerAddMailRsp
	(*PbItem)(nil),              // 4: g1.protocol.PbItem
	(*Ret)(nil),                 // 5: g1.protocol.Ret
}
var file_mailsvr_proto_depIdxs = []int32{
	4, // 0: g1.protocol.PbMail.attach_list:type_name -> g1.protocol.PbItem
	0, // 1: g1.protocol.MailInfo.mail_list:type_name -> g1.protocol.PbMail
	0, // 2: g1.protocol.MailInnerAddMailReq.mail_list:type_name -> g1.protocol.PbMail
	5, // 3: g1.protocol.MailInnerAddMailRsp.ret:type_name -> g1.protocol.Ret
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mailsvr_proto_init() }
func file_mailsvr_proto_init() {
	if File_mailsvr_proto != nil {
		return
	}
	file_common_proto_init()
	file_role_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mailsvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mailsvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mailsvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailInnerAddMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mailsvr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailInnerAddMailRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mailsvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mailsvr_proto_goTypes,
		DependencyIndexes: file_mailsvr_proto_depIdxs,
		MessageInfos:      file_mailsvr_proto_msgTypes,
	}.Build()
	File_mailsvr_proto = out.File
	file_mailsvr_proto_rawDesc = nil
	file_mailsvr_proto_goTypes = nil
	file_mailsvr_proto_depIdxs = nil
}
