// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: mysqlsvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EMysqlType int32

const (
	EMysqlType__MYSQL_TYPE_NONE     EMysqlType = 0
	EMysqlType_MYSQL_TYPE_ROLE_INFO EMysqlType = 1 //    MYSQL_TYPE_ROLE_DATA = 116;
)

// Enum value maps for EMysqlType.
var (
	EMysqlType_name = map[int32]string{
		0: "_MYSQL_TYPE_NONE",
		1: "MYSQL_TYPE_ROLE_INFO",
	}
	EMysqlType_value = map[string]int32{
		"_MYSQL_TYPE_NONE":     0,
		"MYSQL_TYPE_ROLE_INFO": 1,
	}
)

func (x EMysqlType) Enum() *EMysqlType {
	p := new(EMysqlType)
	*p = x
	return p
}

func (x EMysqlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMysqlType) Descriptor() protoreflect.EnumDescriptor {
	return file_mysqlsvr_proto_enumTypes[0].Descriptor()
}

func (EMysqlType) Type() protoreflect.EnumType {
	return &file_mysqlsvr_proto_enumTypes[0]
}

func (x EMysqlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMysqlType.Descriptor instead.
func (EMysqlType) EnumDescriptor() ([]byte, []int) {
	return file_mysqlsvr_proto_rawDescGZIP(), []int{0}
}

// MYSQL_INNER_UPDATE_ROLE_INFO_REQ
type MysqlInnerUpdateRoleInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MysqlInnerUpdateRoleInfoReq) Reset() {
	*x = MysqlInnerUpdateRoleInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysqlsvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlInnerUpdateRoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerUpdateRoleInfoReq) ProtoMessage() {}

func (x *MysqlInnerUpdateRoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_mysqlsvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerUpdateRoleInfoReq.ProtoReflect.Descriptor instead.
func (*MysqlInnerUpdateRoleInfoReq) Descriptor() ([]byte, []int) {
	return file_mysqlsvr_proto_rawDescGZIP(), []int{0}
}

func (x *MysqlInnerUpdateRoleInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MysqlInnerUpdateRoleInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *MysqlInnerUpdateRoleInfoRsp) Reset() {
	*x = MysqlInnerUpdateRoleInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysqlsvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlInnerUpdateRoleInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerUpdateRoleInfoRsp) ProtoMessage() {}

func (x *MysqlInnerUpdateRoleInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mysqlsvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerUpdateRoleInfoRsp.ProtoReflect.Descriptor instead.
func (*MysqlInnerUpdateRoleInfoRsp) Descriptor() ([]byte, []int) {
	return file_mysqlsvr_proto_rawDescGZIP(), []int{1}
}

func (x *MysqlInnerUpdateRoleInfoRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// MYSQL_INNER_SEARCH_ROLE_REQ
type MysqlInnerSearchRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchString string `protobuf:"bytes,1,opt,name=search_string,json=searchString,proto3" json:"search_string,omitempty"`
}

func (x *MysqlInnerSearchRoleReq) Reset() {
	*x = MysqlInnerSearchRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysqlsvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlInnerSearchRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerSearchRoleReq) ProtoMessage() {}

func (x *MysqlInnerSearchRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_mysqlsvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerSearchRoleReq.ProtoReflect.Descriptor instead.
func (*MysqlInnerSearchRoleReq) Descriptor() ([]byte, []int) {
	return file_mysqlsvr_proto_rawDescGZIP(), []int{2}
}

func (x *MysqlInnerSearchRoleReq) GetSearchString() string {
	if x != nil {
		return x.SearchString
	}
	return ""
}

type MysqlInnerSearchRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *Ret   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Uid uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *MysqlInnerSearchRoleRsp) Reset() {
	*x = MysqlInnerSearchRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysqlsvr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlInnerSearchRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerSearchRoleRsp) ProtoMessage() {}

func (x *MysqlInnerSearchRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mysqlsvr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerSearchRoleRsp.ProtoReflect.Descriptor instead.
func (*MysqlInnerSearchRoleRsp) Descriptor() ([]byte, []int) {
	return file_mysqlsvr_proto_rawDescGZIP(), []int{3}
}

func (x *MysqlInnerSearchRoleRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *MysqlInnerSearchRoleRsp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_mysqlsvr_proto protoreflect.FileDescriptor

var file_mysqlsvr_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x1b, 0x4d,
	0x79, 0x73, 0x71, 0x6c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x41,
	0x0a, 0x1b, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65,
	0x74, 0x22, 0x3e, 0x0a, 0x17, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x22, 0x4f, 0x0a, 0x17, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x2a, 0x3c, 0x0a, 0x0a, 0x45, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x5f, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x01,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mysqlsvr_proto_rawDescOnce sync.Once
	file_mysqlsvr_proto_rawDescData = file_mysqlsvr_proto_rawDesc
)

func file_mysqlsvr_proto_rawDescGZIP() []byte {
	file_mysqlsvr_proto_rawDescOnce.Do(func() {
		file_mysqlsvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_mysqlsvr_proto_rawDescData)
	})
	return file_mysqlsvr_proto_rawDescData
}

var file_mysqlsvr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mysqlsvr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mysqlsvr_proto_goTypes = []interface{}{
	(EMysqlType)(0),                     // 0: g1.protocol.EMysqlType
	(*MysqlInnerUpdateRoleInfoReq)(nil), // 1: g1.protocol.MysqlInnerUpdateRoleInfoReq
	(*MysqlInnerUpdateRoleInfoRsp)(nil), // 2: g1.protocol.MysqlInnerUpdateRoleInfoRsp
	(*MysqlInnerSearchRoleReq)(nil),     // 3: g1.protocol.MysqlInnerSearchRoleReq
	(*MysqlInnerSearchRoleRsp)(nil),     // 4: g1.protocol.MysqlInnerSearchRoleRsp
	(*Ret)(nil),                         // 5: g1.protocol.Ret
}
var file_mysqlsvr_proto_depIdxs = []int32{
	5, // 0: g1.protocol.MysqlInnerUpdateRoleInfoRsp.ret:type_name -> g1.protocol.Ret
	5, // 1: g1.protocol.MysqlInnerSearchRoleRsp.ret:type_name -> g1.protocol.Ret
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mysqlsvr_proto_init() }
func file_mysqlsvr_proto_init() {
	if File_mysqlsvr_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mysqlsvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlInnerUpdateRoleInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysqlsvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlInnerUpdateRoleInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysqlsvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlInnerSearchRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysqlsvr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlInnerSearchRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mysqlsvr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mysqlsvr_proto_goTypes,
		DependencyIndexes: file_mysqlsvr_proto_depIdxs,
		EnumInfos:         file_mysqlsvr_proto_enumTypes,
		MessageInfos:      file_mysqlsvr_proto_msgTypes,
	}.Build()
	File_mysqlsvr_proto = out.File
	file_mysqlsvr_proto_rawDesc = nil
	file_mysqlsvr_proto_goTypes = nil
	file_mysqlsvr_proto_depIdxs = nil
}
