//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: struct_config.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropType PropertyType `protobuf:"varint,1,opt,name=PropType,proto3,enum=g1.protocol.PropertyType" json:"PropType,omitempty"` // 道具类型
	Quality  QualityType  `protobuf:"varint,2,opt,name=Quality,proto3,enum=g1.protocol.QualityType" json:"Quality,omitempty"`    // 品质
	Star     uint32       `protobuf:"varint,3,opt,name=Star,proto3" json:"Star,omitempty"`                                       // 星级
	Add      int64        `protobuf:"varint,4,opt,name=Add,proto3" json:"Add,omitempty"`                                         // 道具数量
}

func (x *Reward) Reset() {
	*x = Reward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_struct_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_struct_config_proto_rawDescGZIP(), []int{0}
}

func (x *Reward) GetPropType() PropertyType {
	if x != nil {
		return x.PropType
	}
	return PropertyType_PropertyType_Empty
}

func (x *Reward) GetQuality() QualityType {
	if x != nil {
		return x.Quality
	}
	return QualityType_QualityType_None
}

func (x *Reward) GetStar() uint32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Reward) GetAdd() int64 {
	if x != nil {
		return x.Add
	}
	return 0
}

var File_struct_config_proto protoreflect.FileDescriptor

var file_struct_config_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x1a, 0x11, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x12, 0x35, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x50,
	0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x67, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x41, 0x64,
	0x64, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_struct_config_proto_rawDescOnce sync.Once
	file_struct_config_proto_rawDescData = file_struct_config_proto_rawDesc
)

func file_struct_config_proto_rawDescGZIP() []byte {
	file_struct_config_proto_rawDescOnce.Do(func() {
		file_struct_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_struct_config_proto_rawDescData)
	})
	return file_struct_config_proto_rawDescData
}

var file_struct_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_struct_config_proto_goTypes = []interface{}{
	(*Reward)(nil),    // 0: g1.protocol.Reward
	(PropertyType)(0), // 1: g1.protocol.PropertyType
	(QualityType)(0),  // 2: g1.protocol.QualityType
}
var file_struct_config_proto_depIdxs = []int32{
	1, // 0: g1.protocol.Reward.PropType:type_name -> g1.protocol.PropertyType
	2, // 1: g1.protocol.Reward.Quality:type_name -> g1.protocol.QualityType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_struct_config_proto_init() }
func file_struct_config_proto_init() {
	if File_struct_config_proto != nil {
		return
	}
	file_enum_config_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_struct_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_struct_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_struct_config_proto_goTypes,
		DependencyIndexes: file_struct_config_proto_depIdxs,
		MessageInfos:      file_struct_config_proto_msgTypes,
	}.Build()
	File_struct_config_proto = out.File
	file_struct_config_proto_rawDesc = nil
	file_struct_config_proto_goTypes = nil
	file_struct_config_proto_depIdxs = nil
}
