// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.1
// source: texassvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InnerCreateRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *RoomBaseInfo `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *InnerCreateRoomReq) Reset() {
	*x = InnerCreateRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_texassvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerCreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerCreateRoomReq) ProtoMessage() {}

func (x *InnerCreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_texassvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerCreateRoomReq.ProtoReflect.Descriptor instead.
func (*InnerCreateRoomReq) Descriptor() ([]byte, []int) {
	return file_texassvr_proto_rawDescGZIP(), []int{0}
}

func (x *InnerCreateRoomReq) GetBase() *RoomBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_texassvr_proto protoreflect.FileDescriptor

var file_texassvr_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x78, 0x61, 0x73, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0a, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x12, 0x49, 0x6e, 0x6e,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x2d, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x67, 0x31, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_texassvr_proto_rawDescOnce sync.Once
	file_texassvr_proto_rawDescData = file_texassvr_proto_rawDesc
)

func file_texassvr_proto_rawDescGZIP() []byte {
	file_texassvr_proto_rawDescOnce.Do(func() {
		file_texassvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_texassvr_proto_rawDescData)
	})
	return file_texassvr_proto_rawDescData
}

var file_texassvr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_texassvr_proto_goTypes = []interface{}{
	(*InnerCreateRoomReq)(nil), // 0: g1.protocol.InnerCreateRoomReq
	(*RoomBaseInfo)(nil),       // 1: g1.protocol.RoomBaseInfo
}
var file_texassvr_proto_depIdxs = []int32{
	1, // 0: g1.protocol.InnerCreateRoomReq.base:type_name -> g1.protocol.RoomBaseInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_texassvr_proto_init() }
func file_texassvr_proto_init() {
	if File_texassvr_proto != nil {
		return
	}
	file_room_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_texassvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerCreateRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_texassvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_texassvr_proto_goTypes,
		DependencyIndexes: file_texassvr_proto_depIdxs,
		MessageInfos:      file_texassvr_proto_msgTypes,
	}.Build()
	File_texassvr_proto = out.File
	file_texassvr_proto_rawDesc = nil
	file_texassvr_proto_goTypes = nil
	file_texassvr_proto_depIdxs = nil
}
